### ISSUE TITLE
Question, really

### ISSUE THREAD

**Issue by twhite96** [fidalgodev/fidalgo_info#2]
How did you get the Tooltips on the exact items you wanted them to be? I am trying to wrap my head around this.

I've looked at your code and am not sure _where_ that part is. I know you have an Image Container wrapped around your Gatsby Image component, and you've made a couple of arrays, I get all that but I still don't understand how to place them on the _exact_ item in the image. 

Can you give some tips or guidance?

Thanks

**Comment by fidalgodev** [comment]
The tooltips are just absolute `div`s inside the image wrapper. Image wrapper has position relative. All the tooltips are `siblings` of the image, with `position: absolute` relative to the image (the wrapper in this case).

Then I just get all the tooltips from [here](https://github.com/fidalgodev/fidalgo_info/edit/master/src/content/setup/homeItems.md) and has you can see they have top/left position. I then use this to position each tooltip. 

`<TooltipWrapper selected={opened} key={i} top={top} left={left}>`
